# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32, verbose_name='Company')),
                ('address', models.CharField(max_length=32, verbose_name='Address')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('complement', models.CharField(max_length=32, verbose_name='Complement')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('contact', models.CharField(max_length=32, verbose_name='Contact')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('comments', models.CharField(max_length=32, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='InkVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=96)),
                ('typtinta', models.CharField(choices=[(b'0', b'Solvente'), (b'1', b'Sublimatica'), (b'2', b'UV'), (b'3', b'N/A')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=8, verbose_name='Numero de Serie')),
                ('typtinta', models.CharField(choices=[(b'0', b'Solvente'), (b'1', b'Sublimatica'), (b'2', b'UV'), (b'3', b'N/A')], max_length=24)),
                ('install', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.CharField(max_length=120)),
                ('client_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=8, verbose_name='Model')),
                ('heads', models.PositiveIntegerField(verbose_name='Heads')),
                ('scan', models.PositiveIntegerField(verbose_name='Scan Life')),
                ('pump', models.PositiveIntegerField(verbose_name='Pump Life')),
                ('felt', models.PositiveIntegerField(verbose_name='Felt Life')),
                ('tube', models.PositiveIntegerField(verbose_name='Tube Life')),
                ('wipe', models.PositiveIntegerField(verbose_name='Wiper Life')),
                ('uvlamp', models.PositiveIntegerField(verbose_name='UVLamp Life')),
            ],
        ),
        migrations.CreateModel(
            name='Peck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmware', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Versao do Firmware')),
                ('pSerial', models.CharField(db_index=True, default=b'AABBCCE', max_length=8, verbose_name='Numero de Serie')),
                ('pModelo', models.CharField(db_index=True, default=None, max_length=8, verbose_name='Model')),
                ('createDate', models.DateField(verbose_name='Data do Relatorio')),
                ('ink', models.CharField(max_length=32, verbose_name='Tipo de Tinta')),
                ('bat', models.CharField(max_length=16, verbose_name='Estado da Bateria')),
                ('feed', models.PositiveIntegerField(default=1, verbose_name='Motor Feed')),
                ('scan', models.PositiveIntegerField(default=1, verbose_name='Motor Scan')),
                ('pump', models.PositiveIntegerField(default=1, verbose_name='Pump Scan')),
                ('limp', models.PositiveIntegerField(default=1, verbose_name='Menu Cleaning')),
                ('clean', models.PositiveIntegerField(default=1, verbose_name='Last Head Clean')),
                ('wipe', models.PositiveIntegerField(default=1, verbose_name='Wiping Count')),
                ('liq', models.PositiveIntegerField(default=1, verbose_name='Liquido na Garrafa')),
                ('filepath', models.FileField(default=b'dummy-file', upload_to=b'uploaded/')),
                ('machine_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Machine')),
                ('model_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Modelo')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='model_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Modelo'),
        ),
    ]
