# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0002_auto_20180708_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peck',
            name='ink_vendor',
        ),
    ]
