# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0002_auto_20181016_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='machine',
            name='typtinta',
            field=models.CharField(blank=True, choices=[(b'0', b'Solvente'), (b'1', b'Sublimatica'), (b'2', b'UV'), (b'3', b'N/A')], max_length=24),
        ),
    ]
