# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0003_remove_peck_ink_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='model_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Modelo'),
        ),
    ]
