# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0004_auto_20181016_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Client'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peck.Modelo'),
        ),
    ]
