# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0006_auto_20181016_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='peck',
            name='upldate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
