# Generated by Django 2.2.2 on 2019-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0007_peck_upldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkvendor',
            name='typtinta',
            field=models.CharField(choices=[('0', 'Solvente'), ('1', 'Sublimatica'), ('2', 'UV'), ('3', 'N/A')], max_length=24),
        ),
        migrations.AlterField(
            model_name='machine',
            name='typtinta',
            field=models.CharField(blank=True, choices=[('0', 'Solvente'), ('1', 'Sublimatica'), ('2', 'UV'), ('3', 'N/A')], max_length=24),
        ),
        migrations.AlterField(
            model_name='peck',
            name='filepath',
            field=models.FileField(default='dummy-file', upload_to='uploaded/'),
        ),
        migrations.AlterField(
            model_name='peck',
            name='pSerial',
            field=models.CharField(db_index=True, default='AABBCCE', max_length=8, verbose_name='Numero de Serie'),
        ),
    ]
