# Generated by Django 2.2.2 on 2019-07-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0008_auto_20190624_2313'),
        ('peck', '0008_auto_20190706_1633'),
    ]

    operations = [
    ]
